openapi: 3.0.3
info:
  title: LottiesPeriod - Auth Service API
  description: |
    Authentication and integration with Zitadel IdP for LottiesPeriod platform.
    Handles login, logout, token exchange, and session management.
    
    **Authentication**: All endpoints except `/auth/login` and `/auth/register` require Bearer JWT token in Authorization header.
  version: 1.0.0
  contact:
    name: LottiesPeriod API Support

servers:
  - url: https://6463711e-6d80-462d-b8f5-630be77a4bfd.mock.pstmn.io/v1
    description: Postman Mock Server
  - url: https://api.lottiesperiod.com/v1
    description: Production server
  - url: https://staging-api.lottiesperiod.com/v1
    description: Staging server
  - url: http://localhost:8080/v1
    description: Local development server

tags:
  - name: Authentication
    description: Login, registration, and session management with Zitadel IdP

security:
  - BearerAuth: []

paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Create a new user account linked to Zitadel identity provider
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/login:
    post:
      tags:
        - Authentication
      summary: Login user
      description: Authenticate user and return JWT token
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successfully authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh access token
      description: Get a new access token using refresh token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
                  description: The refresh token
      responses:
        '200':
          description: New access token generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /auth/logout:
    post:
      tags:
        - Authentication
      summary: Logout user
      description: Invalidate current session and tokens
      responses:
        '204':
          description: Successfully logged out
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token issued by Zitadel IdP

  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
        - firstName
        - lastName
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
        password:
          type: string
          format: password
          minLength: 8
          example: "SecureP@ssw0rd"
        firstName:
          type: string
          example: "Jane"
        lastName:
          type: string
          example: "Doe"
        dateOfBirth:
          type: string
          format: date
          example: "1995-06-15"

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
        password:
          type: string
          format: password
          example: "SecureP@ssw0rd"

    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: JWT access token
          example: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9..."
        refreshToken:
          type: string
          description: Refresh token for obtaining new access tokens
          example: "rt_dGVzdF9yZWZyZXNoX3Rva2Vu"
        expiresIn:
          type: integer
          description: Token expiration time in seconds
          example: 3600
        tokenType:
          type: string
          example: "Bearer"
        user:
          $ref: '#/components/schemas/UserProfile'

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        externalId:
          type: string
          description: Zitadel subject ID
          example: "254678324567832456"
        email:
          type: string
          format: email
          example: "user@example.com"
        firstName:
          type: string
          example: "Jane"
        lastName:
          type: string
          example: "Doe"
        dateOfBirth:
          type: string
          format: date
          example: "1995-06-15"
          nullable: true
        profileImageUrl:
          type: string
          format: uri
          example: "https://cdn.lottiesperiod.com/profiles/user123.jpg"
          nullable: true
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-11-20T14:22:00Z"

    UpdateProfileRequest:
      type: object
      properties:
        firstName:
          type: string
          example: "Jane"
        lastName:
          type: string
          example: "Doe"
        dateOfBirth:
          type: string
          format: date
          example: "1995-06-15"
        profileImageUrl:
          type: string
          format: uri
          example: "https://cdn.lottiesperiod.com/profiles/user123.jpg"

    Consent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "660e8400-e29b-41d4-a716-446655440001"
        userId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        consentType:
          type: string
          enum:
            - HEALTH_DATA_COLLECTION
            - PUSH_NOTIFICATIONS
            - ANALYTICS
            - MARKETING
          example: "HEALTH_DATA_COLLECTION"
        granted:
          type: boolean
          example: true
        grantedAt:
          type: string
          format: date-time
          example: "2024-11-20T14:22:00Z"
          nullable: true
        revokedAt:
          type: string
          format: date-time
          nullable: true
        version:
          type: string
          description: Version of the consent agreement
          example: "1.0"

    UpdateConsentRequest:
      type: object
      required:
        - consentType
        - granted
      properties:
        consentType:
          type: string
          enum:
            - HEALTH_DATA_COLLECTION
            - PUSH_NOTIFICATIONS
            - ANALYTICS
            - MARKETING
          example: "HEALTH_DATA_COLLECTION"
        granted:
          type: boolean
          example: true
        version:
          type: string
          example: "1.0"

    NotificationPreference:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "770e8400-e29b-41d4-a716-446655440002"
        userId:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        notificationType:
          type: string
          enum:
            - PERIOD_REMINDER
            - FERTILE_WINDOW
            - OVULATION
            - SYMPTOM_LOG_REMINDER
            - CONTENT_RECOMMENDATION
          example: "PERIOD_REMINDER"
        enabled:
          type: boolean
          example: true
        advanceNotice:
          type: integer
          description: Days before event to send notification
          example: 1
          nullable: true
        timeOfDay:
          type: string
          format: time
          description: Preferred time for notification (HH:MM)
          example: "09:00"
          nullable: true
        createdAt:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-11-20T14:22:00Z"

    UpdateNotificationPreferencesRequest:
      type: object
      required:
        - preferences
      properties:
        preferences:
          type: array
          items:
            type: object
            required:
              - notificationType
              - enabled
            properties:
              notificationType:
                type: string
                enum:
                  - PERIOD_REMINDER
                  - FERTILE_WINDOW
                  - OVULATION
                  - SYMPTOM_LOG_REMINDER
                  - CONTENT_RECOMMENDATION
              enabled:
                type: boolean
              advanceNotice:
                type: integer
                minimum: 0
                maximum: 7
              timeOfDay:
                type: string
                format: time

    Error:
      type: object
      properties:
        code:
          type: string
          example: "INVALID_REQUEST"
        message:
          type: string
          example: "The request contains invalid data"
        details:
          type: object
          additionalProperties: true
          nullable: true
        timestamp:
          type: string
          format: date-time
          example: "2024-11-20T14:22:00Z"
